cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-cask-fonts'
tap 'homebrew/cask-cask-drivers'

brew 'ack'
brew 'blueutil'
brew 'coreutils'
brew 'felixkratz/formulae/sketchybar'
brew 'ffmpeg'
brew 'gbevin/tools/sendmidi'
brew 'glow'
brew 'grc'
brew 'homebrew/cask/mediainfo'
brew 'ical-buddy'
brew 'imagemagick'
brew 'libusb'
brew 'locateme'
brew 'navi'
brew 'neofetch'
brew 'node'
brew 'openssl'
brew 'pyenv'
brew 'sendmidi'
brew 'shellcheck'
brew 'shfmt'
brew 'smudge/smudge/nightlight'
brew 'somafm'
# brew 'switchaudio-osx'
brew 'terminal-notifier'
brew 'tiptop'
brew 'wget'
brew 'yabai'
brew 'yt-dlp'

# Apps

# cask 'alfred'
cask 'arc'
cask 'audacity'
# cask 'batchmod'
cask 'colorpicker-skalacolor'
cask 'cyberduck'
cask 'discord'
cask 'figma'
cask 'handbrake'
cask 'iina'
cask 'imageoptim'
cask 'iterm2'
cask 'jdownloader'
cask 'karabiner-elements'
cask 'menuwhere'
# cask 'kicad'
cask 'numi'
cask 'plexamp'
cask 'popcorn-time'
cask 'private-internet-access'
cask 'raycast'
cask 'simple-comic'
cask 'syntax-highlight'
cask 'the-unarchiver'
cask 'torbrowser'
cask 'vscodium'
cask 'xld'

# Quicklook plugins (https://github.com/sindresorhus/quick-look-plugins#install-all)
brew 'iloveitaly/tap/qlzipinfo'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlmobi'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-json'
cask 'quicklookase'
cask 'suspicious-package'
cask 'webpquicklook'

# Fonts
brew 'font-fira-code-nerd-font'
brew 'font-hack-nerd-font'
brew 'font-iosevka-term-nerd-font'
brew 'font-jetbrains-mono-nerd-font'
brew 'font-roboto-mono-nerd-font'
cask 'font-caskaydia-cove-nerd-font'
cask 'sf-symbols'