#!/bin/sh

DIR="$( cd "$( dirname "$0" )" && pwd )/switch"

show_menu(){
    NORMAL=`echo "\033[m"`
    MENU=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"`
    ENTER_LINE=`echo "\033[33m"`
    echo "${MENU}**************SWITCH TOOLKIT*****************${NORMAL}"
    echo "${MENU}${NUMBER} 1)${NORMAL} Boot Payload ${NORMAL}"
    echo "${MENU}${NUMBER} 2)${NORMAL} Fluffy ${NORMAL}"
    echo "${MENU}${NUMBER} 3)${NORMAL} Tinfoil USB Install ${NORMAL}"
    echo "${MENU}${NUMBER} 4)${NORMAL} SD Card Cleanup ${NORMAL}"
    echo "${MENU}*********************************************${NORMAL}"
    echo "${ENTER_LINE}Choose a menu option or hit ${RED_TEXT}Enter${ENTER_LINE} to exit. ${NORMAL}"
    read opt
}
function option_picked() {
    COLOR='\033[01;31m' # bold red
    RESET='\033[00;00m' # normal white
    MESSAGE=${@:-"${RESET}Error: No message passed"}
    echo "${COLOR}${MESSAGE}${RESET}"
}

clear
show_menu
while [ opt != '' ]
    do
    if [[ $opt = "" ]]; then
            exit;
    else
        case $opt in
        1) clear;
        option_picked "**************Boot Payload**************";
        python3 $DIR/fusee-launcher.py $DIR/hekate.bin
        show_menu;
        ;;

        2) clear;
        option_picked "**************Fluffy**************";
        python3 $DIR/fluffy.pyw
        show_menu;
        ;;

        3) clear;
        option_picked "**************Tinfoil USB Install**************";
        python3 $DIR/usb_install_pc.py ~/Desktop/
        show_menu;
        ;;

        4) clear;
        option_picked "**************SD Card Cleanup**************";
        $DIR/switch-cleanup
        show_menu;
        ;;

        *)clear;
        option_picked "Pick an option from the menu:";
        show_menu;
        ;;
    esac
fi
done
