alias reload!='. ~/.zshrc'

alias ll='ls -la'
alias cl='clear'
alias cls='clear'
alias markdownhelp='open http://j.mp/144z4kR'
alias dirsizes='du -skh *(/)'
alias dotpull='cd ~/.dotfiles ; git pl'
alias cheat='glow ~/.dotfiles/Cheat\ Sheet.md'
alias e='nano'
alias yabai.update='~/.config/yabai/update.sh'
