# export PATH="/usr/local/opt/ruby/bin/:$PATH"
# export PATH="$HOME/.gem/ruby/2.7.0/bin/:$PATH"
export PATH="/usr/local/sbin/:$PATH"
export PATH="$HOME/.dotfiles/bin/:$PATH"
export PATH="$HOME/.config/.spicetify/:$PATH"
export PATH="$HOME/Library/Python/3.11/bin/:$PATH"